spring:



  datasource: #디폴트인 h2 는 별도 설정없어도 된다.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/registdb?serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update  #기본 create and drop, update(db 유지) create: 테이블이 이미 있다면 drop하고 다시 create한다.
    properties:
      hibernate:
        format_sql: true # 실행되는 query를 보여줌

  session:
    store-type: jdbc
    jdbc.initialize-schema: always


    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html

logging.level:
  org.hibernate.SQL: debug

