spring:

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:   # 2 는 기본 인메모리 방식 . tcp 방식을 ㅐ줘야 정보 휘발 x crud 가 올바르게 h2 콘솔에 반영된다.
    url: jdbc:h2:tcp://localhost/~/test # test 부분을 자신이 원하는 것으로 바꾸시면 됩니다.
    username: sa # username과 password는 자신의 설정에 맞게
    password:
    driver-class-name: org.h2.Driver
    data: classpath:import.sql
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update  #기본 create and drop, update(db 유지) create: 테이블이 이미 있다면 drop하고 다시 create한다.
    properties:
      hibernate:
        format_sql: true # 실행되는 query를 보여줌

  session:
    store-type: jdbc
    jdbc.initialize-schema: always


    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html

logging.level:
  org.hibernate.SQL: debug

